services:
  - type: web
    name: MyStory
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: mystory-db  # Match the name of your Render PostgreSQL DB
          property: connectionString
    staticPublishPath: staticfiles
