# Generated by Django 5.1.4 on 2025-06-26 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0005_alter_chapter_content'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='chapters.chapter'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='date_taken',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
