# Generated by Django 5.1.5 on 2025-03-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
