# Generated by Django 5.1.5 on 2025-03-04 00:58

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0002_alter_chapter_content_alter_chapter_subtitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
