# Generated by Django 5.1.5 on 2025-03-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0003_alter_chapter_options_alter_chapter_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(default=999),
        ),
    ]
