# Generated by Django 5.1.5 on 2025-03-07 01:37

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0004_alter_chapter_options_alter_chapter_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
